export const identityAbi = [
  {
    type: 'function',
    name: 'mint',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'faceCommitment', type: 'bytes32' },
    ],
    outputs: [{ name: 'tokenId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'mintSelf',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'faceCommitment', type: 'bytes32' }],
    outputs: [{ name: 'tokenId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'walletToTokenId',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'identities',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'faceCommitment', type: 'bytes32' },
      { name: 'status', type: 'uint8' },
      { name: 'version', type: 'uint32' },
    ],
  },
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'verifier',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'distanceThreshold',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'setVerifier',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newVerifier', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setDistanceThreshold',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newThreshold', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'verifyFaceProof',
    stateMutability: 'view',
    inputs: [
      { name: 'tokenId', type: 'uint256' },
      { name: 'a', type: 'uint256[2]' },
      { name: 'b', type: 'uint256[2][2]' },
      { name: 'c', type: 'uint256[2]' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
];
